### ISSUE TITLE
Logstash maybe_wp_debug_log_entries TypeError

### ISSUE THREAD

**Issue by bgrgicak** [Automattic/vip-go-mu-plugins#1534]
## Expected/Desired Behavior

Fill with either one:

1. Expected behavior for bugs

An existing log message should be passed to `wp_debug_log` in `\Automattic\VIP\Logstash\Logger::maybe_wp_debug_log_entries`. This should be a single message not the entire `$entries` array.

## Actual Behavior

In the [last update](https://github.com/Automattic/vip-go-mu-plugins/commit/18edec4834b64d8600023c299bf81d8f81c1c0b2#diff-3838a9a3a25b6317431ca9b67654d9aeR508) to the `\Automattic\VIP\Logstash\Logger::maybe_wp_debug_log_entries` method a non-exisitng variable `$entry` is passed to `wp_debug_log`.

## Steps to Reproduce the Problem

1. Make sure your local environment will try to store log data to `debug.log` by setting `VIP_GO_ENV` to `false` and `WP_DEBUG` to `true`
2. Create a log message by calling `log2logstash`
3. See the `TypeError` in the PHP error log

## (Optional) Additional notes

`debug.log` error message

```
[01-Apr-2020 10:02:20 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WCCOM\Logstash::wp_debug_log() must be of the type array, null given, called in /var/www/html/wp-content/mu-plugins/class-logger.php on line 508 and defined in /var/www/html/wp-content/plugins/wccom-plugins/logger/includes/class-logstash.php:32
Stack trace:
#0 /var/www/html/wp-content/mu-plugins/class-logger.php(508): WCCOM\Logstash::wp_debug_log(NULL)
#1 /var/www/html/wp-content/mu-plugins/class-logger.php(477): Automattic\VIP\Logstash\Logger::maybe_wp_debug_log_entries(Array)
#2 /var/www/html/wp-includes/class-wp-hook.php(288): Automattic\VIP\Logstash\Logger::process_entries_on_shutdown('')
#3 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /var/www/html/wp-includes/load.php(947): do_action('shutdown')
#6 [internal function]: shutdown_action_hook()
#7 {main}
  thrown in /var/www/html/wp-content/plugins/wccom-plugins/logger/includes/class-logstash.php on line 32
[01-Apr-2020 10:02:20 UTC] PHP Stack trace:
[01-Apr-2020 10:02:20 UTC] PHP   1. {main}() /var/www/html/index.php:0
[01-Apr-2020 10:02:20 UTC] PHP   2. require() /var/www/html/index.php:17
[01-Apr-2020 10:02:20 UTC] PHP   3. require_once() /var/www/html/wp-blog-header.php:19
[01-Apr-2020 10:02:20 UTC] PHP   4. do_action($tag = *uninitialized*, ...$arg = variadic()) /var/www/html/wp-includes/template-loader.php:13
[01-Apr-2020 10:02:20 UTC] PHP   5. WP_Hook->do_action($args = *uninitialized*) /var/www/html/wp-includes/plugin.php:478
[01-Apr-2020 10:02:20 UTC] PHP   6. WP_Hook->apply_filters($value = *uninitialized*, $args = *uninitialized*) /var/www/html/wp-includes/class-wp-hook.php:312
[01-Apr-2020 10:02:20 UTC] PHP   7. WC_AJAX::do_wc_ajax(*uninitialized*) /var/www/html/wp-includes/class-wp-hook.php:288
[01-Apr-2020 10:02:20 UTC] PHP   8. do_action($tag = *uninitialized*, ...$arg = variadic()) /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:89
[01-Apr-2020 10:02:20 UTC] PHP   9. WP_Hook->do_action($args = *uninitialized*) /var/www/html/wp-includes/plugin.php:478
[01-Apr-2020 10:02:20 UTC] PHP  10. WP_Hook->apply_filters($value = *uninitialized*, $args = *uninitialized*) /var/www/html/wp-includes/class-wp-hook.php:312
[01-Apr-2020 10:02:20 UTC] PHP  11. WC_AJAX::update_order_review(*uninitialized*) /var/www/html/wp-includes/class-wp-hook.php:288
[01-Apr-2020 10:02:20 UTC] PHP  12. wp_send_json($response = *uninitialized*, $status_code = *uninitialized*) /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:388
[01-Apr-2020 10:02:20 UTC] PHP  13. wp_die($message = *uninitialized*, $title = *uninitialized*, $args = *uninitialized*) /var/www/html/wp-includes/functions.php:3975
[01-Apr-2020 10:02:20 UTC] PHP  14. _ajax_wp_die_handler($message = *uninitialized*, $title = *uninitialized*, $args = *uninitialized*) /var/www/html/wp-includes/functions.php:3291
```

**Comment by nickdaugherty** [comment]
cc @hanifn
