### ISSUE TITLE
Failed to register_groups; cannot be called after the `send_headers` hook has fired

### ISSUE THREAD

**Issue by sjinks** [Automattic/vip-go-mu-plugins#5192]
```
1) Automattic\VIP\Cache\Vary_Cache_Test::test__is_user_in_group with data set "user-not-yet-assigned" (array(), array('dev-group'), 'dev-group', false)
ErrorException: Failed to register_groups (dev-group); cannot be called after the `send_headers` hook has fired.

/home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/tests/cache/test-vary-cache.php:38
/home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/cache/class-vary-cache.php:198
/home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/tests/cache/test-vary-cache.php:230
```

Ref: https://github.com/Automattic/vip-go-mu-plugins/actions/runs/7659791176/job/20875697039?pr=5191
Random Seed: 1706212988

**Comment by sjinks** [comment]
Parse.ly: option_disabled: 1706212998, WP 6.4.2
Parse.ly: 3.1 option_disabled: 1706212988, WP 6.4.2

**Comment by sjinks** [comment]
A similar one:

```
1) Automattic\VIP\Cache\Vary_Cache_Test::test__is_user_in_group with data set "group-not-defined" (array(), array(), 'dev-group', false)
ErrorException: Failed to register_groups (); cannot be called after the `send_headers` hook has fired.

/home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/tests/cache/test-vary-cache.php:38
/home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/cache/class-vary-cache.php:198
/home/runner/work/vip-go-mu-plugins/vip-go-mu-plugins/tests/cache/test-vary-cache.php:230
```

WP nightly (6.5-alpha-57345), multisite: yes, JP: yes, PHP: 8.3, seed: 1706213085

**Comment by sjinks** [comment]
Repro:

```sh
WPVIP_PARSELY_INTEGRATION_TEST_MODE="option_disabled" ./bin/test.sh --php 8.0 --order-by=random --random-order-seed=1706221292 --stop-on-error
```

**Comment by sjinks** [comment]
With this patch:

```diff
diff --git a/cache/class-vary-cache.php b/cache/class-vary-cache.php
index 1415b187b..bcbc0ddd7 100644
--- a/cache/class-vary-cache.php
+++ b/cache/class-vary-cache.php
@@ -2,6 +2,7 @@
 
 namespace Automattic\VIP\Cache;
 
+use Exception;
 use WP_Error;
 
 class Vary_Cache {
@@ -33,6 +34,10 @@ class Vary_Cache {
         */
        private static $did_send_headers = false;
 
+       public static function did_send_headers() {
+               return self::$did_send_headers;
+       }
+
        /**
         * Flag to indicate if we're in nocache mode.
         *
@@ -509,6 +514,9 @@ class Vary_Cache {
         */
        public static function send_headers() {
                if ( ! self::$did_send_headers ) {
+                       fprintf( STDERR, ( new Exception() )->getTraceAsString() );
+                       fflush( STDERR );
+
                        self::$did_send_headers = true;
 
                        $sent_vary   = self::send_vary_headers();
diff --git a/tests/cache/test-vary-cache.php b/tests/cache/test-vary-cache.php
index b7f0c2e88..4b219c446 100644
--- a/tests/cache/test-vary-cache.php
+++ b/tests/cache/test-vary-cache.php
@@ -25,6 +25,8 @@ class Vary_Cache_Test extends WP_UnitTestCase {
 
                header_remove();
 
+               self::assertFalse( Vary_Cache::did_send_headers() );
+
                Vary_Cache::load();
                Constant_Mocker::clear();
 
```

we get this:

```
.............................................................   61 / 1454 (  4%)
.............................................................  122 / 1454 (  8%)
.........S...............S...................................  183 / 1454 ( 12%)
......................S............SSSSS............SSSS.....  244 / 1454 ( 16%)
....SS.......................................................  305 / 1454 ( 20%)
..............................................S..............  366 / 1454 ( 25%)
...............S...............#0 /wordpress/wordpress-6.4.2/wp-includes/class-wp-hook.php(324): Automattic\VIP\Cache\Vary_Cache::send_headers()
#1 /wordpress/wordpress-6.4.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /wordpress/wordpress-6.4.2/wp-includes/plugin.php(565): WP_Hook->do_action()
#3 /wordpress/wordpress-6.4.2/wp-includes/class-wp.php(590): do_action_ref_array()
#4 /wordpress/wordpress-6.4.2/wp-includes/class-wp.php(821): WP->send_headers()
#5 /wordpress/wordpress-6.4.2/wp-includes/functions.php(1336): WP->main()
#6 /wordpress/wordpress-6.4.2/wp-admin/includes/post.php(1374): wp()
#7 /home/circleci/project/tests/performance/test-class-mime-types-caching.php(192): wp_edit_attachments_query()
#8 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1612): Automattic\VIP\Performance\Mime_Types_Caching_Test->test__media_library_form_output()
#9 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(1218): PHPUnit\Framework\TestCase->runTest()
#10 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#11 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestCase.php(968): PHPUnit\Framework\TestResult->run()
#12 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestCase->run()
#13 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run()
#14 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run()
#15 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run()
#16 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run()
#17 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#18 /home/circleci/project/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#19 /home/circleci/project/vendor/bin/phpunit(123): include('...')
#20 {main}...........S..................  427 / 1454 ( 29%)
......................SS..............S......................  488 / 1454 ( 33%)
.............................................................  549 / 1454 ( 37%)
..........................S..................................  610 / 1454 ( 41%)
..SSSSSSSSSSSF
```

`test-class-mime-types-caching.php` invokes `wp_edit_attachments_query()`; this results in `send_headers()`. Ultimately, `Automattic\VIP\Cache\Vary_Cache::send_headers()` sets `$did_send_headers` to `true`. And because the test class does not reset the internal state, tests start with `$did_send_headers === true` and fail.

**Comment by sjinks** [comment]
`Vary_Cache` gets loaded when PHPUnit checks `tests/cache/test-vary-cache.php`:

```
#0 /home/circleci/project/tests/cache/test-vary-cache.php(10): require_once()
#1 /home/circleci/project/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('...')
#2 /home/circleci/project/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
#3 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(397): PHPUnit\Util\FileLoader::checkAndLoad()
#4 /home/circleci/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(536): PHPUnit\Framework\TestSuite->addTestFile()
#5 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles()
#6 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(391): PHPUnit\TextUI\TestSuiteMapper->map()
#7 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments()
#8 /home/circleci/project/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#9 /home/circleci/project/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#10 /home/circleci/project/vendor/bin/phpunit(123): include('...')
#11 {main}
```

**Comment by sjinks** [comment]
This patch should fix the issue:

```diff
diff --git a/tests/cache/test-vary-cache.php b/tests/cache/test-vary-cache.php
index b7f0c2e88..82535fc7e 100644
--- a/tests/cache/test-vary-cache.php
+++ b/tests/cache/test-vary-cache.php
@@ -7,7 +7,6 @@ use ErrorException;
 use WP_UnitTestCase;
 
 require_once __DIR__ . '/mock-header.php';
-require_once __DIR__ . '/../../cache/class-vary-cache.php';
 
 // phpcs:disable WordPressVIPMinimum.Variables.RestrictedVariables.cache_constraints___COOKIE
 // phpcs:disable WordPress.PHP.DiscouragedPHPFunctions.runtime_configuration_error_reporting
@@ -17,6 +16,11 @@ class Vary_Cache_Test extends WP_UnitTestCase {
        private $original_server;
        private $original_error_reporting;
 
+       public static function wpSetUpBeforeClass() {
+               require_once __DIR__ . '/../../cache/class-vary-cache.php';
+               Vary_Cache::unload();
+       }
+
        public function setUp(): void {
                parent::setUp();
 
```
