### ISSUE TITLE
Class 'Automattic\WP\Cron_Control\REST_API' not found in /var/www/html/wp-content/mu-plugins/001-cron.php

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#662]
Trying to install mu-plugins in a local environment, there's a fatal error in the API related to cron control. I suspect we're assuming cron control is always active, but it's not active by default in local environments.

```
Fatal error</b>:  Uncaught Error: Class 'Automattic\WP\Cron_Control\REST_API' not found in /var/www/html/wp-content/mu-plugins/001-cron.php:43
```

Full error:

```
$ curl -i http://wp.local:8000/wp-json/wp/v2/
HTTP/1.1 200 OK
Server: nginx/1.11.8
Date: Mon, 19 Jun 2017 20:59:04 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Robots-Tag: noindex
Link: <http://wp.local:8000/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Automattic\WP\Cron_Control\REST_API' not found in /var/www/html/wp-content/mu-plugins/001-cron.php:43
Stack trace:
#0 /usr/src/wordpress/wp-includes/class-wp-hook.php(298): wpcom_vip_permit_cron_control_rest_access(true)
#1 /usr/src/wordpress/wp-includes/plugin.php(203): WP_Hook-&gt;apply_filters(true, Array)
#2 /usr/src/wordpress/wp-includes/rest-api/class-wp-rest-server.php(140): apply_filters('rest_authentica...', NULL)
#3 /usr/src/wordpress/wp-includes/rest-api/class-wp-rest-server.php(320): WP_REST_Server-&gt;check_authentication()
#4 /usr/src/wordpress/wp-includes/rest-api.php(267): WP_REST_Server-&gt;serve_request('/wp/v2')
#5 /usr/src/wordpress/wp-includes/class-wp-hook.php(298): rest_api_loaded(Object(WP))
#6 /usr/src/wordpress/wp-includes/class-wp-hook.php(323): WP_Hook-&gt;apply_filters(NULL, Array)
#7 /usr/src/wordpress/wp-includes/plugin.php(515): WP_Hook-&gt;do_action(Array)
#8 /usr/src/wordpress/wp-includes/class-wp.php(386): do_action_ref_array('parse_request', Array)
#9 /usr/src/wordp in <b>/var/www/html/wp-content/mu-plugins/001-cron.php</b> on line <b>43</b><br />
```

**Comment by mjangda** [comment]
#652

**Comment by joshbetz** [comment]
Oh nice, that looks better.
